version: 2.1

orbs:
    lambda-dev: lambdatest/lambda-tunnel@volatile

workflows:      
    basic_workflow:
        jobs:
          - lambdatest/with_tunnel:
              name: "Chrome test"
              tunnel_name: "chrome"
              steps:
                - run: 
                    command: |
                      npm install
                      node_modules/.bin/nightwatch -e chrome
          - lambdatest/with_tunnel:
              name: "Firefox test"
              tunnel_name: "firefox"
              steps:
                - run: 
                    command: |
                      npm install
                      node_modules/.bin/nightwatch -e firefox
